name: Docker Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Deploy to EC2 and Run Docker
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 13.202.46.178
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Stop old container if running
          docker stop docker1 || true
          docker rm docker1 || true

          # Remove old repo if needed
          rm -rf ~/project-1-maven-jenkins-CICD-docker-eks-

          # Clone your actual repo to EC2
          git clone https://github.com/swathichaganti91/project-1-maven-jenkins-CICD-docker-eks-.git
          cd project-1-maven-jenkins-CICD-docker-eks-

          # Build Docker image
          docker build -t docker1 .

          # Run container
          docker run -d -p 8075:8080 --name docker1 docker1

          # Optional: Show logs
          docker ps -a
