name: Docker Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 13.202.46.178
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Clone the repo if not already present
          cd ~/project-1-maven-jenkins-CICD-docker-eks- || \
          git clone https://github.com/swathichaganti91/project-1-maven-jenkins-CICD-docker-eks-.git && \
          cd project-1-maven-jenkins-CICD-docker-eks-

          # Stop and remove existing container if running
          docker stop docker1 || true
          docker rm docker1 || true

          # Build Docker image
          docker build -t docker1 .

          # Run container with port 8075 and assign name
          docker run -p 8075:8080 -dt --name docker1 docker1

          # Log for debugging
          docker ps -a
          docker logs docker1 || true
