name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t docker1 .

    - name: Run Docker container
      run: docker run -p 8075:8080 -d docker1

    - name: Success Message
      if: success()
      run: echo "App deployed on http://13.202.46.178:8075"

    - name: Failure Message
      if: failure()
      run: echo "Build failed"
